### ISSUE TITLE
 OperationException(linkException: null, graphqlErrors: [GraphQLError(message: Internal server error, locations: null, path: null, extensions: null)])

### ISSUE THREAD

**Issue by Hemant301** [bagisto/opensource-ecommerce-mobile-app#12]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
Add screenshots to help explain your problem.

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AnchitAndroidWorld** [comment]
Please considering adding data so that we can check if this is a bug or not.

Closing this as "No Relevant Data Provided".
