### ISSUE TITLE
Getting errors in flutter app

### ISSUE THREAD

**Issue by Abhijittribhuvan** [bagisto/opensource-ecommerce-mobile-app#14]
**Describe the bug**
There are issues are coming related to the gradle and related issues.

FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':location' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.20

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 20s
Running Gradle task 'assembleRelease'...                           21.2s
Gradle task assembleRelease failed with exit code 1

this is a error, and i fix other errors also , but it is getting too much error, i  tried another flutter project that are working, if is it possible then can anyone give me the updated repository, where there is no need to update versions

**Comment by AnchitAndroidWorld** [comment]
You are getting the issue with the environment and set up of the flutter version in the project and their dependencies.

Currently, for this part, only you have to fix this on your system.

I think you should use the flutter version manager tool and then set up the versions of the Flutter environment correctly as mentioned in the pubspec.yaml file.

Once you complete this setup, you will probably face no issues and errors.


Now Coming on to the issue mentioned in your logs, you just need to update the location package to a higher version that can support the Gradle plugin version 1.5.20

Check for the location package details over pub dev and then modify the code accordingly.

If you want us to support the latest Flutter, Gradle, Android and iOS versions, then wait for the next release in the future or if you want support on priority then contact the sales team for paid support https://bagisto.com/en/contacts/
