### ISSUE TITLE
Can't run the app on Android

### ISSUE THREAD

**Issue by eddoperes** [bagisto/opensource-ecommerce-mobile-app#16]
**Describe the bug**

When I run the app on Android simulator return the error 
"Failed to Invoke: No deep link found."

**To Reproduce**
Download the source code
Configure server_configuration.dart

const String baseUrl = "http://localhost/bagisto/public/graphql";
const String defaultWebsiteId = "1";
const String defaultChannelId = "1";
const String defaultStoreCode = "pt-br";
const String defaultChannelName = "com.webkul.bagisto_mobikul/channel";
const String defaultCurrencyCode = "BLR";
const String storage = "storage/";
List<String> supportedLocale = ['en', 'fr', 'nl', 'tr', 'es', 'ar', 'pt_br'];

**Expected behavior**
The app run and show products

**Screenshots**
?

**Smartphone (please complete the following information):**
sdk_gphone_86_64
Android 13

**Additional context**
?

**Comment by AnchitAndroidWorld** [comment]
@eddoperes :

NO Android device would understand the URL named http://localhost/ as the android device will try to locate this with in the android device only.

If you are trying to run the Android application in a local environment then map your system with a permanent IP address and then use that IP address as the base Url 

Or if you are using any public server with a domain mapped then use that domain name and complete URL as your baseURL.


Hope this solves your issue.

Still if you find something then you can always re-open this issue and we will help you out.

For now, we are closing this issue.

**Comment by eddoperes** [comment]
Thanks for replay

I changed the server_configuration.dart e replaced

const String baseUrl = "http://localhost/bagisto/public/graphql";

with

const String baseUrl = "http://10.0.2.2/bagisto/public/graphql";

Of course the Android emulator will think localhost is the phone, my mistake.

But I replaced localhost with 10.0.2.2 and Flutter knows 10.0.2.2 is the machine hosting the emulator (I have already used 10.0.2.2 in others projetcs and worked) and even so the problem persist 

"Failed to Invoke: No deep link found."

**Comment by AnchitAndroidWorld** [comment]
Hey @eddoperes  

Please share the complete logcat details.

there are logs below the COOKIE DATA as well.

I need to check those and then I will be in a state to answer your queries.


P.S  -> Have you tried opening the baseUrl in the browser of the same android phone ? Is it working ?

**Comment by eddoperes** [comment]
![Screenshot_1724244990](https://github.com/user-attachments/assets/ca13d35b-ea87-41eb-909e-63598e17d806)

**Comment by eddoperes** [comment]
I don't know much about GraphQL. For me is more common use REST. But I think that GraphQL is working.

**Comment by eddoperes** [comment]
I could not find this folder logcat. I didn't find COOKIE DATA as well. Were are it? Is in the apache server? Is in Flutter project?

**Comment by AnchitAndroidWorld** [comment]
Hey @eddoperes : for the url part in the browser edit the address and make sure that the website is accessible to you in the android device itself.

For the logcat, this is the output printed in the DebugConsole window of your Visual Studio Code Editor for the flutter code when you run the flutter code.

Please do share me the complete OUTPUT 
In the earlier provided screenshot as well the OUTPUT is printing  and there is a print line "COOKIE DATA", I need the output below that to check what exactly is happening

**Comment by eddoperes** [comment]
[logcat.txt](https://github.com/user-attachments/files/16692745/logcat.txt)

**Comment by eddoperes** [comment]
I copied the contents of logcat window of Android Studio

**Comment by eddoperes** [comment]
[vscode.txt](https://github.com/user-attachments/files/16692935/vscode.txt)

**Comment by eddoperes** [comment]
[vscode.txt](https://github.com/user-attachments/files/16695570/vscode.txt)

**Comment by eddoperes** [comment]
I copied the contents of vscode console too

**Comment by eddoperes** [comment]
[vscode.txt](https://github.com/user-attachments/files/16695639/vscode.txt)

**Comment by eddoperes** [comment]
I copied the contents of vscode console too

**Comment by eddoperes** [comment]
![Screenshot_1724261009](https://github.com/user-attachments/assets/b3a82995-177a-403c-873d-bb02577f537e)

**Comment by eddoperes** [comment]
After ignoring the errors the result is above

**Comment by AnchitAndroidWorld** [comment]
Hey @eddoperes : have you enabled any categories on the homepage of the website ?

**Comment by vivek-webkul** [comment]
Hi @eddoperes 

Hope you are doing well!

Can you let us know which version of Bagisto you are using? The open-source version of [Bagisto Mobile App](https://github.com/bagisto/opensource-ecommerce-mobile-app) is compatible with Bagisto v2.0.0. 

So to install & configure the [Bagisto Headless API](https://github.com/bagisto/headless-ecommerce) you have to clone the project by using  the below command:

**composer require bagisto/graphql-api ^v2.0.2**

**Note:-** The below command will provide you the code from the master branch, which is not the stable version:
**composer require bagisto/graphql-api dev-main**

In case you are still facing some issues regarding setting up the project, you can raise a ticket to our support team at [support@webkul.com](mailto:support@bagisto.com)

Thanks & Regards,
Bagisto Support Team

**Comment by eddoperes** [comment]
I have read the errors message in Flutter console and find this one:

"Failed to find class User in namespaces [App, App\Models] for directive @paginate."

What could be wrong?

**Comment by eddoperes** [comment]
No progress yet.

This is the error appearing in VSCode console:

EXCEPTION -> OperationException(linkException: ServerException(originalException: ClientException: Connection reset by peer, uri=http://10.0.2.2/bagisto221/bagisto/public/graphql, originalStackTrace: #0      IOClient.send

**Comment by vivek-webkul** [comment]
> I executed -> composer require bagisto/graphql-api ^v2.0.2

Hi @eddoperes ,

Can you let us know which version of Bagisto you are using? The open-source version of [Bagisto Mobile App](https://github.com/bagisto/opensource-ecommerce-mobile-app) is compatible with Bagisto v2.0.0.

Thanks & Regards,
Bagisto Support Team

**Comment by vivek-webkul** [comment]
Hi @eddoperes,

> But not this version v2.0.0. Where can I find it? It's not on github.

You can find the Headless version v2.0.2 (API version) which is for Bagisto v2.0.0:
https://github.com/bagisto/headless-ecommerce/tree/v2.0.2
https://github.com/bagisto/headless-ecommerce/tree/v2.0.2?tab=readme-ov-file#1-requirements

You can use the below command to clone API via composer:
composer require bagisto/graphql-api ^v2.0.2

Thanks & Regards,
Bagisto Support Team
