### ISSUE TITLE
Compatibility with latest graphql version

### ISSUE THREAD

**Issue by slyd4r** [bagisto/opensource-ecommerce-mobile-app#20]
**Describe the bug**
There have been a lot of updates in the latest graphql version(2.2.2) , mutations do not match. 
**To Reproduce**
Setting up bagisto graphql and tested, graphql is working on the browser and postman

**Expected behavior**
Expected to work on flutter application but got a lot of mutation errors. (example :pagination of all products).

**Comment by AnchitAndroidWorld** [comment]
Hey @slyd4r : 

We do understand your concern and are working on migrating the flutter app to support 2.2.2 bagisto version and latest graphql version.

As the code of the app states it currently supports till version 2.0.0, so we recommend you using the compatible graphql version only. 
[https://github.com/bagisto/headless-ecommerce/tree/v2.0.2](https://github.com/bagisto/headless-ecommerce/tree/v2.0.2) 

Further, we are expecting to release a 2.2.2 compatible version in next week, if you want you can wait till then.

**Comment by AnchitAndroidWorld** [comment]
Hey @slyd4r : 

A new release is out for this project, please do check that.
