### ISSUE TITLE
Why am I receiving an Internal server error for the themeCustomization query path in my GraphQL operation?

### ISSUE THREAD

**Issue by mebron** [bagisto/opensource-ecommerce-mobile-app#21]
[log] 
EXCEPTION -> OperationException(linkException: null, graphqlErrors: [GraphQLError(message: Internal server error, locations: [ErrorLocation(line: 3, column: 3)], path: [themeCustomization], extensions: null)])

**Comment by vivek-webkul** [comment]
Hi @mebron,

Thank you for using Bagisto!

Could you please provide the complete query schema for theme customization, or share a short video demonstrating the issue? This will help us better understand your concerns.

Additionally, please let us know the versions of [Bagisto](https://github.com/bagisto/bagisto) and [Headless](https://github.com/bagisto/headless-ecommerce/) you’re using.

Thanks!

**Comment by mebron** [comment]
Hi,

Thanks for reaching out!

I’m currently using Bagisto V 2.2.3, along with opensource-ecommerce-mobile-app v 2.2.2 and headless-ecommerce v 2.2.2. I’ve also customized the theme by cloning the default shop theme. However, an error occurs when I run 'flutter run'.

Thanks again for your assistance!

**Comment by mayank-webkul** [comment]
Hello @mebron 

The Open Source E-commerce Mobile App v2.2.2 and Headless E-commerce v2.2.2 are not available for Bagisto v2.2.3. This may be the reason you're encountering this issue.

**Comment by mebron** [comment]
Hi,

I’ve downgraded Bagisto to V 2.2.2, but the same error persists. Please see the Laravel log for details on the error:

[2024-10-28 13:10:42] production.ERROR: Undefined array key "filters" {"exception":"[object] (ErrorException(code: 0): Undefined array key \"filters\" at /var/www/jumlakart.com/vendor/bagisto/graphql-api/src/Queries/Shop/Common/HomePageQuery.php:100)
[stacktrace]
#0 /var/www/jumlakart.com/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(255): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/jumlakart.com/vendor/bagisto/graphql-api/src/Queries/Shop/Common/HomePageQuery.php(100): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#2 [internal function]: Webkul\\GraphQLAPI\\Queries\\Shop\\Common\\HomePageQuery->Webkul\\GraphQLAPI\\Queries\\Shop\\Common\\{closure}()
#3 /var/www/jumlakart.com/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(558): array_map()
#4 /var/www/jumlakart.com/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(777): Illuminate\\Support\\Arr::map()
#5 /var/www/jumlakart.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Collection.php(344): Illuminate\\Support\\Collection->map()
#6 /var/www/jumlakart.com/vendor/bagisto/graphql-api/src/Queries/Shop/Common/HomePageQuery.php(66): Illuminate\\Database\\Eloquent\\Collection->map()
#7 /var/www/jumlakart.com/vendor/nuwave/lighthouse/src/Schema/Values/FieldValue.php(189): Webkul\\GraphQLAPI\\Queries\\Shop\\Common\\HomePageQuery->getThemeCustomizationData()
#8 /var/www/jumlakart.com/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(758): Nuwave\\Lighthouse\\Schema\\Values\\FieldValue->Nuwave\\Lighthouse\\Schema\\Values\\{closure}()
#9 /var/www/jumlakart.com/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(669): GraphQL\\Executor\\ReferenceExecutor->resolveFieldValueOrError()
#10 /var/www/jumlakart.com/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(1383): GraphQL\\Executor\\ReferenceExecutor->resolveField()
#11 /var/www/jumlakart.com/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(314): GraphQL\\Executor\\ReferenceExecutor->executeFields()
#12 /var/www/jumlakart.com/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(252): GraphQL\\Executor\\ReferenceExecutor->executeOperation()
#13 /var/www/jumlakart.com/vendor/webonyx/graphql-php/src/Executor/Executor.php(184): GraphQL\\Executor\\ReferenceExecutor->doExecute()
#14 /var/www/jumlakart.com/vendor/webonyx/graphql-php/src/GraphQL.php(163): GraphQL\\Executor\\Executor::promiseToExecute()
#15 /var/www/jumlakart.com/vendor/webonyx/graphql-php/src/GraphQL.php(97): GraphQL\\GraphQL::promiseToExecute()
#16 /var/www/jumlakart.com/vendor/nuwave/lighthouse/src/GraphQL.php(146): GraphQL\\GraphQL::executeQuery()
#17 /var/www/jumlakart.com/vendor/nuwave/lighthouse/src/GraphQL.php(110): Nuwave\\Lighthouse\\GraphQL->executeParsedQueryRaw()
#18 /var/www/jumlakart.com/vendor/nuwave/lighthouse/src/GraphQL.php(90): Nuwave\\Lighthouse\\GraphQL->executeParsedQuery()
#19 /var/www/jumlakart.com/vendor/nuwave/lighthouse/src/GraphQL.php(240): Nuwave\\Lighthouse\\GraphQL->executeQueryString()
#20 /var/www/jumlakart.com/vendor/nuwave/lighthouse/src/GraphQL.php(203): Nuwave\\Lighthouse\\GraphQL->executeOperation()
#21 /var/www/jumlakart.com/vendor/nuwave/lighthouse/src/Support/Utils.php(107): Nuwave\\Lighthouse\\GraphQL->Nuwave\\Lighthouse\\{closure}()
#22 /var/www/jumlakart.com/vendor/nuwave/lighthouse/src/GraphQL.php(201): Nuwave\\Lighthouse\\Support\\Utils::mapEach()
#23 /var/www/jumlakart.com/vendor/nuwave/lighthouse/src/Http/GraphQLController.php(32): Nuwave\\Lighthouse\\GraphQL->executeOperationOrOperations()
#24 /var/www/jumlakart.com/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(46): Nuwave\\Lighthouse\\Http\\GraphQLController->__invoke()
#25 /var/www/jumlakart.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php(259): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#26 /var/www/jumlakart.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#27 /var/www/jumlakart.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(806): Illuminate\\Routing\\Route->run()
#28 /var/www/jumlakart.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#29 /var/www/jumlakart.com/vendor/bagisto/graphql-api/src/Http/Middleware/RateLimitMiddleware.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 /var/www/jumlakart.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Webkul\\GraphQLAPI\\Http\\Middleware\\RateLimitMiddleware->handle()
#31 /var/www/jumlakart.com/vendor/bagisto/graphql-api/src/Http/Middleware/CurrencyMiddleware.php(33): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /var/www/jumlakart.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Webkul\\GraphQLAPI\\Http\\Middleware\\CurrencyMiddleware->handle()
#33 /var/www/jumlakart.com/vendor/bagisto/graphql-api/src/Http/Middleware/LocaleMiddleware.php(33): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /var/www/jumlakart.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Webkul\\GraphQLAPI\\Http\\Middleware\\LocaleMiddleware->handle()
#35 /var/www/jumlakart.com/vendor/nuwave/lighthouse/src/Http/Middleware/AttemptAuthentication.php(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /var/www/jumlakart.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Nuwave\\Lighthouse\\Http\\Middleware\\AttemptAuthentication->handle()
#37 /var/www/jumlakart.com/vendor/nuwave/lighthouse/src/Http/Middleware/AcceptJson.php(24): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /var/www/jumlakart.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Nuwave\\Lighthouse\\Http\\Middleware\\AcceptJson->handle()
#39 /var/www/jumlakart.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /var/www/jumlakart.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(805): Illuminate\\Pipeline\\Pipeline->then()
#41 /var/www/jumlakart.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(784): Illuminate\\Routing\\Router->runRouteWithinStack()
#42 /var/www/jumlakart.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(748): Illuminate\\Routing\\Router->runRoute()
#43 /var/www/jumlakart.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(737): Illuminate\\Routing\\Router->dispatchToRoute()
#44 /var/www/jumlakart.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch()
#45 /var/www/jumlakart.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#46 /var/www/jumlakart.com/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(59): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 /var/www/jumlakart.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle()
#48 /var/www/jumlakart.com/packages/Webkul/Installer/src/Http/Middleware/CanInstall.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#49 /var/www/jumlakart.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Webkul\\Installer\\Http\\Middleware\\CanInstall->handle()
#50 /var/www/jumlakart.com/packages/Webkul/Core/src/Http/Middleware/SecureHeaders.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#51 /var/www/jumlakart.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Webkul\\Core\\Http\\Middleware\\SecureHeaders->handle()
#52 /var/www/jumlakart.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#53 /var/www/jumlakart.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#54 /var/www/jumlakart.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#55 /var/www/jumlakart.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#56 /var/www/jumlakart.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#57 /var/www/jumlakart.com/packages/Webkul/Core/src/Http/Middleware/CheckForMaintenanceMode.php(93): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#58 /var/www/jumlakart.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Webkul\\Core\\Http\\Middleware\\CheckForMaintenanceMode->handle()
#59 /var/www/jumlakart.com/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#60 /var/www/jumlakart.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\HandleCors->handle()
#61 /var/www/jumlakart.com/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#62 /var/www/jumlakart.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#63 /var/www/jumlakart.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#64 /var/www/jumlakart.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then()
#65 /var/www/jumlakart.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#66 /var/www/jumlakart.com/public/index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle()
#67 {main}
"}

**Comment by mayank-webkul** [comment]
@mebron Could you please provide the complete query schema for theme customization?

**Comment by mebron** [comment]
Hi,

I didn't change any query schema for the theme customization; I only renamed the default shop theme as per the documentation.

Thank you!

**Comment by mayank-webkul** [comment]
Ok, but please provide the query schema for this so that we can check.

**Comment by mebron** [comment]
Hi,

I’m new to Bagisto, so I’m not entirely sure how to retrieve the complete query schema details. Could you guide me on how to access or generate this schema information so I can share it with you?

Thanks for your patience!

**Comment by mayank-webkul** [comment]
Hi @mebron,

The issue has been resolved, and the PR has been merged into the main branch. You can now access the updated code.

PR Link: [Headless Ecommerce PR #351](https://github.com/bagisto/headless-ecommerce/pull/351)
