### ISSUE TITLE
There are some generated class which does not generate automatically. please add the instructions for generating those class.

### ISSUE THREAD

**Issue by kapilb145** [bagisto/opensource-ecommerce-mobile-app#4]
Please mention the solution for the problem. i can say that on every class where this issue indicate has same format

***_model.g.dart
![Screenshot 2024-01-17 at 5 20 23 PM](https://github.com/bagisto/opensource-ecommerce-mobile-app/assets/25499719/77c75c35-8c63-4811-8d0a-e407264c2127)

**Comment by AnchitAndroidWorld** [comment]
@kapilb145  :  can you please share the flutter doctor command report for your system ?

**Comment by AnchitAndroidWorld** [comment]
@kapilb145  : 

A normal solution to what you are experiencing will be executing the build command of the uild_runner package.

`flutter pub run build_runner build `

or 

`dart run build_runner build `

depending on your  flutter version.

Recommending using the flag `--delete-conflicting-outputs `

So your final command in the terminal for solving the issue will be 


`flutter pub run build_runner build --delete-conflicting-outputs`

or 

`dart run build_runner build --delete-conflicting-outputs`
