### ISSUE TITLE
Flutter web

### ISSUE THREAD

**Issue by nyck33** [bagisto/opensource-ecommerce-mobile-app#6]
Is it possible to extend this as a flutter web app so I don't have to make two front ends.  Flutter basically is one code base for multiple platforms but the way you have it I'd have to possibly make changes to the flutter code for mobile and then to the JavaScript code for the main laravel app right?

**Comment by RishabhYogi-Webkul** [comment]
Hello @nyck33 

Yes, it is possible to extend this as a flutter web app we have made two front-ends because sometimes client requirements are been different for desktop and app respectively. 

As of now, this is an opensource platform so you can customize it as per your requirements and can create a single frontend as well according to your needs.

Thanks & Regards..!!

**Comment by ajayjoshioutdosolutions** [comment]
The Android app is not functioning correctly after integrating the GraphQL API with graphql dev-main and Bagisto 2.2. We are still encountering errors related to translation keys in the GraphQL API response.
pls suggest @RishabhYogi-Webkul @vivek-webkul @AnchitAndroidWorld @nyck33 
![Screenshot from 2024-08-
[request-parms and response.txt](https://github.com/user-attachments/files/16635090/request-parms.and.response.txt)
16 14-23-04](https://github.com/user-attachments/assets/97baabaf-4cc0-4ae2-8ca6-83fc3d166761)

**Comment by AnchitAndroidWorld** [comment]
@ajayjoshioutdosolutions  : This application supports only bagisto version 2.0.0 as mentioned in the readme of this project as well.
<img width="2245" alt="Screenshot 2024-08-16 at 2 52 08 PM" src="https://github.com/user-attachments/assets/c9f56d98-a1f7-4db0-8350-52fbff451920">

**Comment by vivek-webkul** [comment]
Hi,

@nyck33 and @ajayjoshioutdosolutions
https://www.awesomescreenshot.com/image/50074098?key=5ead1f8bb20c8d35476f8bca4264626b

I hope your queries have been resolved and answered, for now closing this issue. If you have any other queries or doubts, just reopen the same ticket by putting your comment here.

Thanks & Regards,
Bagisto Support Team
