### ISSUE TITLE
run first time flutter app

### ISSUE THREAD

**Issue by nadeemabualarayes** [bagisto/opensource-ecommerce-mobile-app#7]
Target of URI hasn't been generated: 'package:bagisto_app_demo/data_model/account_models/account_update_model.g.dart'. (Documentation)

Target of URI hasn't been generated: 'package:bagisto_app_demo/data_model/account_models/account_info_details.g.dart'. (Documentation)

try to run it but does not work 

<img width="1710" alt="Screenshot 2024-05-09 at 3 38 58 PM" src="https://github.com/bagisto/opensource-ecommerce-mobile-app/assets/66251426/e508e0e3-081f-4897-be8e-42977e0970af">

**Comment by AnchitAndroidWorld** [comment]
you can use build command of the build_runner package to generate the missing model files.


`dart run build_runner build --delete-conflicting-outputs`

if this does not works on the first run try steps below -> 


`flutter clean`

`flutter pub get`

`dart run build_runner build --delete-conflicting-outputs`

and this should help you
