### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by GoutamMMT** [bagisto/opensource-ecommerce-mobile-app#9]
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > AAPT2 aapt2-7.0.4-7396180-windows Daemon #0: Unexpected error during link, attempting to stop daemon.
     This should not happen under normal circumstances, please file an issue if it does.

**Comment by AnchitAndroidWorld** [comment]
@GoutamMMT : please share the complete logcat and output of flutter doctor 

Also please do let us know if you have created any extra XML files in your android application code ?
